apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: xsc3l79tl-java-quarkus
  janus-idp.io/tekton: xsc3l79tl-java-quarkus
  backstage.io/kubernetes-id: xsc3l79tl-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xsc3l79tl-java-quarkus
resources:
- deployment.yaml
- route.yaml
- service.yaml
